// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ltsrpc.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ltsrpc_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ltsrpc_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3009000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3009001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ltsrpc_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ltsrpc_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[8]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ltsrpc_2eproto;
namespace ltsrpc {
class Cluster;
class ClusterDefaultTypeInternal;
extern ClusterDefaultTypeInternal _Cluster_default_instance_;
class GetMembersRequest;
class GetMembersRequestDefaultTypeInternal;
extern GetMembersRequestDefaultTypeInternal _GetMembersRequest_default_instance_;
class GetMembersResponse;
class GetMembersResponseDefaultTypeInternal;
extern GetMembersResponseDefaultTypeInternal _GetMembersResponse_default_instance_;
class GetTxnTimestampCtx;
class GetTxnTimestampCtxDefaultTypeInternal;
extern GetTxnTimestampCtxDefaultTypeInternal _GetTxnTimestampCtx_default_instance_;
class Member;
class MemberDefaultTypeInternal;
extern MemberDefaultTypeInternal _Member_default_instance_;
class RequestHeader;
class RequestHeaderDefaultTypeInternal;
extern RequestHeaderDefaultTypeInternal _RequestHeader_default_instance_;
class ResponseHeader;
class ResponseHeaderDefaultTypeInternal;
extern ResponseHeaderDefaultTypeInternal _ResponseHeader_default_instance_;
class Status;
class StatusDefaultTypeInternal;
extern StatusDefaultTypeInternal _Status_default_instance_;
}  // namespace ltsrpc
PROTOBUF_NAMESPACE_OPEN
template<> ::ltsrpc::Cluster* Arena::CreateMaybeMessage<::ltsrpc::Cluster>(Arena*);
template<> ::ltsrpc::GetMembersRequest* Arena::CreateMaybeMessage<::ltsrpc::GetMembersRequest>(Arena*);
template<> ::ltsrpc::GetMembersResponse* Arena::CreateMaybeMessage<::ltsrpc::GetMembersResponse>(Arena*);
template<> ::ltsrpc::GetTxnTimestampCtx* Arena::CreateMaybeMessage<::ltsrpc::GetTxnTimestampCtx>(Arena*);
template<> ::ltsrpc::Member* Arena::CreateMaybeMessage<::ltsrpc::Member>(Arena*);
template<> ::ltsrpc::RequestHeader* Arena::CreateMaybeMessage<::ltsrpc::RequestHeader>(Arena*);
template<> ::ltsrpc::ResponseHeader* Arena::CreateMaybeMessage<::ltsrpc::ResponseHeader>(Arena*);
template<> ::ltsrpc::Status* Arena::CreateMaybeMessage<::ltsrpc::Status>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace ltsrpc {

enum StatusCode : int {
  SC_OK = 0,
  SC_ERROR = 1,
  SC_UNKNOWN = 2,
  SC_NOT_LEADER = 3,
  SC_NOT_EXISTS = 4,
  SC_CANCEL = 5,
  SC_RESOURCE_EXHAUSTED = 6,
  SC_ABORTED = 7,
  SC_LEADER_NOT_FOUND = 8,
  StatusCode_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  StatusCode_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool StatusCode_IsValid(int value);
constexpr StatusCode StatusCode_MIN = SC_OK;
constexpr StatusCode StatusCode_MAX = SC_LEADER_NOT_FOUND;
constexpr int StatusCode_ARRAYSIZE = StatusCode_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* StatusCode_descriptor();
template<typename T>
inline const std::string& StatusCode_Name(T enum_t_value) {
  static_assert(::std::is_same<T, StatusCode>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function StatusCode_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    StatusCode_descriptor(), enum_t_value);
}
inline bool StatusCode_Parse(
    const std::string& name, StatusCode* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<StatusCode>(
    StatusCode_descriptor(), name, value);
}
// ===================================================================

class Cluster :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ltsrpc.Cluster) */ {
 public:
  Cluster();
  virtual ~Cluster();

  Cluster(const Cluster& from);
  Cluster(Cluster&& from) noexcept
    : Cluster() {
    *this = ::std::move(from);
  }

  inline Cluster& operator=(const Cluster& from) {
    CopyFrom(from);
    return *this;
  }
  inline Cluster& operator=(Cluster&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Cluster& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Cluster* internal_default_instance() {
    return reinterpret_cast<const Cluster*>(
               &_Cluster_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Cluster& a, Cluster& b) {
    a.Swap(&b);
  }
  inline void Swap(Cluster* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Cluster* New() const final {
    return CreateMaybeMessage<Cluster>(nullptr);
  }

  Cluster* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Cluster>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Cluster& from);
  void MergeFrom(const Cluster& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Cluster* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ltsrpc.Cluster";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ltsrpc_2eproto);
    return ::descriptor_table_ltsrpc_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kClusterIdFieldNumber = 1,
  };
  // uint32 cluster_id = 1;
  void clear_cluster_id();
  ::PROTOBUF_NAMESPACE_ID::uint32 cluster_id() const;
  void set_cluster_id(::PROTOBUF_NAMESPACE_ID::uint32 value);

  // @@protoc_insertion_point(class_scope:ltsrpc.Cluster)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::uint32 cluster_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ltsrpc_2eproto;
};
// -------------------------------------------------------------------

class Status :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ltsrpc.Status) */ {
 public:
  Status();
  virtual ~Status();

  Status(const Status& from);
  Status(Status&& from) noexcept
    : Status() {
    *this = ::std::move(from);
  }

  inline Status& operator=(const Status& from) {
    CopyFrom(from);
    return *this;
  }
  inline Status& operator=(Status&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Status& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Status* internal_default_instance() {
    return reinterpret_cast<const Status*>(
               &_Status_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Status& a, Status& b) {
    a.Swap(&b);
  }
  inline void Swap(Status* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Status* New() const final {
    return CreateMaybeMessage<Status>(nullptr);
  }

  Status* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Status>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Status& from);
  void MergeFrom(const Status& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Status* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ltsrpc.Status";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ltsrpc_2eproto);
    return ::descriptor_table_ltsrpc_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMsgFieldNumber = 2,
    kCodeFieldNumber = 1,
  };
  // string msg = 2;
  void clear_msg();
  const std::string& msg() const;
  void set_msg(const std::string& value);
  void set_msg(std::string&& value);
  void set_msg(const char* value);
  void set_msg(const char* value, size_t size);
  std::string* mutable_msg();
  std::string* release_msg();
  void set_allocated_msg(std::string* msg);

  // .ltsrpc.StatusCode code = 1;
  void clear_code();
  ::ltsrpc::StatusCode code() const;
  void set_code(::ltsrpc::StatusCode value);

  // @@protoc_insertion_point(class_scope:ltsrpc.Status)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr msg_;
  int code_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ltsrpc_2eproto;
};
// -------------------------------------------------------------------

class Member :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ltsrpc.Member) */ {
 public:
  Member();
  virtual ~Member();

  Member(const Member& from);
  Member(Member&& from) noexcept
    : Member() {
    *this = ::std::move(from);
  }

  inline Member& operator=(const Member& from) {
    CopyFrom(from);
    return *this;
  }
  inline Member& operator=(Member&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Member& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Member* internal_default_instance() {
    return reinterpret_cast<const Member*>(
               &_Member_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Member& a, Member& b) {
    a.Swap(&b);
  }
  inline void Swap(Member* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Member* New() const final {
    return CreateMaybeMessage<Member>(nullptr);
  }

  Member* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Member>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Member& from);
  void MergeFrom(const Member& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Member* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ltsrpc.Member";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ltsrpc_2eproto);
    return ::descriptor_table_ltsrpc_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPeerUrlsFieldNumber = 3,
    kClientUrlsFieldNumber = 4,
    kNameFieldNumber = 2,
    kMemberIdFieldNumber = 1,
    kLeaderPriorityFieldNumber = 5,
  };
  // repeated string peer_urls = 3;
  int peer_urls_size() const;
  void clear_peer_urls();
  const std::string& peer_urls(int index) const;
  std::string* mutable_peer_urls(int index);
  void set_peer_urls(int index, const std::string& value);
  void set_peer_urls(int index, std::string&& value);
  void set_peer_urls(int index, const char* value);
  void set_peer_urls(int index, const char* value, size_t size);
  std::string* add_peer_urls();
  void add_peer_urls(const std::string& value);
  void add_peer_urls(std::string&& value);
  void add_peer_urls(const char* value);
  void add_peer_urls(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& peer_urls() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_peer_urls();

  // repeated string client_urls = 4;
  int client_urls_size() const;
  void clear_client_urls();
  const std::string& client_urls(int index) const;
  std::string* mutable_client_urls(int index);
  void set_client_urls(int index, const std::string& value);
  void set_client_urls(int index, std::string&& value);
  void set_client_urls(int index, const char* value);
  void set_client_urls(int index, const char* value, size_t size);
  std::string* add_client_urls();
  void add_client_urls(const std::string& value);
  void add_client_urls(std::string&& value);
  void add_client_urls(const char* value);
  void add_client_urls(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& client_urls() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_client_urls();

  // string name = 2;
  void clear_name();
  const std::string& name() const;
  void set_name(const std::string& value);
  void set_name(std::string&& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  std::string* mutable_name();
  std::string* release_name();
  void set_allocated_name(std::string* name);

  // uint64 member_id = 1;
  void clear_member_id();
  ::PROTOBUF_NAMESPACE_ID::uint64 member_id() const;
  void set_member_id(::PROTOBUF_NAMESPACE_ID::uint64 value);

  // int32 leader_priority = 5;
  void clear_leader_priority();
  ::PROTOBUF_NAMESPACE_ID::int32 leader_priority() const;
  void set_leader_priority(::PROTOBUF_NAMESPACE_ID::int32 value);

  // @@protoc_insertion_point(class_scope:ltsrpc.Member)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> peer_urls_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> client_urls_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  ::PROTOBUF_NAMESPACE_ID::uint64 member_id_;
  ::PROTOBUF_NAMESPACE_ID::int32 leader_priority_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ltsrpc_2eproto;
};
// -------------------------------------------------------------------

class RequestHeader :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ltsrpc.RequestHeader) */ {
 public:
  RequestHeader();
  virtual ~RequestHeader();

  RequestHeader(const RequestHeader& from);
  RequestHeader(RequestHeader&& from) noexcept
    : RequestHeader() {
    *this = ::std::move(from);
  }

  inline RequestHeader& operator=(const RequestHeader& from) {
    CopyFrom(from);
    return *this;
  }
  inline RequestHeader& operator=(RequestHeader&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const RequestHeader& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RequestHeader* internal_default_instance() {
    return reinterpret_cast<const RequestHeader*>(
               &_RequestHeader_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(RequestHeader& a, RequestHeader& b) {
    a.Swap(&b);
  }
  inline void Swap(RequestHeader* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline RequestHeader* New() const final {
    return CreateMaybeMessage<RequestHeader>(nullptr);
  }

  RequestHeader* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<RequestHeader>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const RequestHeader& from);
  void MergeFrom(const RequestHeader& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RequestHeader* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ltsrpc.RequestHeader";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ltsrpc_2eproto);
    return ::descriptor_table_ltsrpc_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kClusterIdFieldNumber = 1,
  };
  // uint32 cluster_id = 1;
  void clear_cluster_id();
  ::PROTOBUF_NAMESPACE_ID::uint32 cluster_id() const;
  void set_cluster_id(::PROTOBUF_NAMESPACE_ID::uint32 value);

  // @@protoc_insertion_point(class_scope:ltsrpc.RequestHeader)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::uint32 cluster_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ltsrpc_2eproto;
};
// -------------------------------------------------------------------

class ResponseHeader :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ltsrpc.ResponseHeader) */ {
 public:
  ResponseHeader();
  virtual ~ResponseHeader();

  ResponseHeader(const ResponseHeader& from);
  ResponseHeader(ResponseHeader&& from) noexcept
    : ResponseHeader() {
    *this = ::std::move(from);
  }

  inline ResponseHeader& operator=(const ResponseHeader& from) {
    CopyFrom(from);
    return *this;
  }
  inline ResponseHeader& operator=(ResponseHeader&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ResponseHeader& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ResponseHeader* internal_default_instance() {
    return reinterpret_cast<const ResponseHeader*>(
               &_ResponseHeader_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(ResponseHeader& a, ResponseHeader& b) {
    a.Swap(&b);
  }
  inline void Swap(ResponseHeader* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ResponseHeader* New() const final {
    return CreateMaybeMessage<ResponseHeader>(nullptr);
  }

  ResponseHeader* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ResponseHeader>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ResponseHeader& from);
  void MergeFrom(const ResponseHeader& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ResponseHeader* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ltsrpc.ResponseHeader";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ltsrpc_2eproto);
    return ::descriptor_table_ltsrpc_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStatusFieldNumber = 2,
    kClusterIdFieldNumber = 1,
  };
  // .ltsrpc.Status status = 2;
  bool has_status() const;
  void clear_status();
  const ::ltsrpc::Status& status() const;
  ::ltsrpc::Status* release_status();
  ::ltsrpc::Status* mutable_status();
  void set_allocated_status(::ltsrpc::Status* status);

  // uint32 cluster_id = 1;
  void clear_cluster_id();
  ::PROTOBUF_NAMESPACE_ID::uint32 cluster_id() const;
  void set_cluster_id(::PROTOBUF_NAMESPACE_ID::uint32 value);

  // @@protoc_insertion_point(class_scope:ltsrpc.ResponseHeader)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::ltsrpc::Status* status_;
  ::PROTOBUF_NAMESPACE_ID::uint32 cluster_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ltsrpc_2eproto;
};
// -------------------------------------------------------------------

class GetMembersRequest :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ltsrpc.GetMembersRequest) */ {
 public:
  GetMembersRequest();
  virtual ~GetMembersRequest();

  GetMembersRequest(const GetMembersRequest& from);
  GetMembersRequest(GetMembersRequest&& from) noexcept
    : GetMembersRequest() {
    *this = ::std::move(from);
  }

  inline GetMembersRequest& operator=(const GetMembersRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetMembersRequest& operator=(GetMembersRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const GetMembersRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GetMembersRequest* internal_default_instance() {
    return reinterpret_cast<const GetMembersRequest*>(
               &_GetMembersRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(GetMembersRequest& a, GetMembersRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(GetMembersRequest* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline GetMembersRequest* New() const final {
    return CreateMaybeMessage<GetMembersRequest>(nullptr);
  }

  GetMembersRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<GetMembersRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const GetMembersRequest& from);
  void MergeFrom(const GetMembersRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetMembersRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ltsrpc.GetMembersRequest";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ltsrpc_2eproto);
    return ::descriptor_table_ltsrpc_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHeaderFieldNumber = 1,
  };
  // .ltsrpc.RequestHeader header = 1;
  bool has_header() const;
  void clear_header();
  const ::ltsrpc::RequestHeader& header() const;
  ::ltsrpc::RequestHeader* release_header();
  ::ltsrpc::RequestHeader* mutable_header();
  void set_allocated_header(::ltsrpc::RequestHeader* header);

  // @@protoc_insertion_point(class_scope:ltsrpc.GetMembersRequest)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::ltsrpc::RequestHeader* header_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ltsrpc_2eproto;
};
// -------------------------------------------------------------------

class GetMembersResponse :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ltsrpc.GetMembersResponse) */ {
 public:
  GetMembersResponse();
  virtual ~GetMembersResponse();

  GetMembersResponse(const GetMembersResponse& from);
  GetMembersResponse(GetMembersResponse&& from) noexcept
    : GetMembersResponse() {
    *this = ::std::move(from);
  }

  inline GetMembersResponse& operator=(const GetMembersResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetMembersResponse& operator=(GetMembersResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const GetMembersResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GetMembersResponse* internal_default_instance() {
    return reinterpret_cast<const GetMembersResponse*>(
               &_GetMembersResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(GetMembersResponse& a, GetMembersResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(GetMembersResponse* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline GetMembersResponse* New() const final {
    return CreateMaybeMessage<GetMembersResponse>(nullptr);
  }

  GetMembersResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<GetMembersResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const GetMembersResponse& from);
  void MergeFrom(const GetMembersResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetMembersResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ltsrpc.GetMembersResponse";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ltsrpc_2eproto);
    return ::descriptor_table_ltsrpc_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMembersFieldNumber = 2,
    kHeaderFieldNumber = 1,
    kLeaderFieldNumber = 3,
    kEtcdLeaderFieldNumber = 4,
  };
  // repeated .ltsrpc.Member members = 2;
  int members_size() const;
  void clear_members();
  ::ltsrpc::Member* mutable_members(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ltsrpc::Member >*
      mutable_members();
  const ::ltsrpc::Member& members(int index) const;
  ::ltsrpc::Member* add_members();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ltsrpc::Member >&
      members() const;

  // .ltsrpc.ResponseHeader header = 1;
  bool has_header() const;
  void clear_header();
  const ::ltsrpc::ResponseHeader& header() const;
  ::ltsrpc::ResponseHeader* release_header();
  ::ltsrpc::ResponseHeader* mutable_header();
  void set_allocated_header(::ltsrpc::ResponseHeader* header);

  // .ltsrpc.Member leader = 3;
  bool has_leader() const;
  void clear_leader();
  const ::ltsrpc::Member& leader() const;
  ::ltsrpc::Member* release_leader();
  ::ltsrpc::Member* mutable_leader();
  void set_allocated_leader(::ltsrpc::Member* leader);

  // .ltsrpc.Member etcd_leader = 4;
  bool has_etcd_leader() const;
  void clear_etcd_leader();
  const ::ltsrpc::Member& etcd_leader() const;
  ::ltsrpc::Member* release_etcd_leader();
  ::ltsrpc::Member* mutable_etcd_leader();
  void set_allocated_etcd_leader(::ltsrpc::Member* etcd_leader);

  // @@protoc_insertion_point(class_scope:ltsrpc.GetMembersResponse)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ltsrpc::Member > members_;
  ::ltsrpc::ResponseHeader* header_;
  ::ltsrpc::Member* leader_;
  ::ltsrpc::Member* etcd_leader_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ltsrpc_2eproto;
};
// -------------------------------------------------------------------

class GetTxnTimestampCtx :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ltsrpc.GetTxnTimestampCtx) */ {
 public:
  GetTxnTimestampCtx();
  virtual ~GetTxnTimestampCtx();

  GetTxnTimestampCtx(const GetTxnTimestampCtx& from);
  GetTxnTimestampCtx(GetTxnTimestampCtx&& from) noexcept
    : GetTxnTimestampCtx() {
    *this = ::std::move(from);
  }

  inline GetTxnTimestampCtx& operator=(const GetTxnTimestampCtx& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetTxnTimestampCtx& operator=(GetTxnTimestampCtx&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const GetTxnTimestampCtx& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GetTxnTimestampCtx* internal_default_instance() {
    return reinterpret_cast<const GetTxnTimestampCtx*>(
               &_GetTxnTimestampCtx_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(GetTxnTimestampCtx& a, GetTxnTimestampCtx& b) {
    a.Swap(&b);
  }
  inline void Swap(GetTxnTimestampCtx* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline GetTxnTimestampCtx* New() const final {
    return CreateMaybeMessage<GetTxnTimestampCtx>(nullptr);
  }

  GetTxnTimestampCtx* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<GetTxnTimestampCtx>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const GetTxnTimestampCtx& from);
  void MergeFrom(const GetTxnTimestampCtx& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetTxnTimestampCtx* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ltsrpc.GetTxnTimestampCtx";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ltsrpc_2eproto);
    return ::descriptor_table_ltsrpc_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTxnIdFieldNumber = 1,
    kTxnTsFieldNumber = 2,
  };
  // uint64 txn_id = 1;
  void clear_txn_id();
  ::PROTOBUF_NAMESPACE_ID::uint64 txn_id() const;
  void set_txn_id(::PROTOBUF_NAMESPACE_ID::uint64 value);

  // uint64 txn_ts = 2;
  void clear_txn_ts();
  ::PROTOBUF_NAMESPACE_ID::uint64 txn_ts() const;
  void set_txn_ts(::PROTOBUF_NAMESPACE_ID::uint64 value);

  // @@protoc_insertion_point(class_scope:ltsrpc.GetTxnTimestampCtx)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::uint64 txn_id_;
  ::PROTOBUF_NAMESPACE_ID::uint64 txn_ts_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ltsrpc_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Cluster

// uint32 cluster_id = 1;
inline void Cluster::clear_cluster_id() {
  cluster_id_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Cluster::cluster_id() const {
  // @@protoc_insertion_point(field_get:ltsrpc.Cluster.cluster_id)
  return cluster_id_;
}
inline void Cluster::set_cluster_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {

  cluster_id_ = value;
  // @@protoc_insertion_point(field_set:ltsrpc.Cluster.cluster_id)
}

// -------------------------------------------------------------------

// Status

// .ltsrpc.StatusCode code = 1;
inline void Status::clear_code() {
  code_ = 0;
}
inline ::ltsrpc::StatusCode Status::code() const {
  // @@protoc_insertion_point(field_get:ltsrpc.Status.code)
  return static_cast< ::ltsrpc::StatusCode >(code_);
}
inline void Status::set_code(::ltsrpc::StatusCode value) {

  code_ = value;
  // @@protoc_insertion_point(field_set:ltsrpc.Status.code)
}

// string msg = 2;
inline void Status::clear_msg() {
  msg_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& Status::msg() const {
  // @@protoc_insertion_point(field_get:ltsrpc.Status.msg)
  return msg_.GetNoArena();
}
inline void Status::set_msg(const std::string& value) {

  msg_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ltsrpc.Status.msg)
}
inline void Status::set_msg(std::string&& value) {

  msg_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ltsrpc.Status.msg)
}
inline void Status::set_msg(const char* value) {
  GOOGLE_DCHECK(value != nullptr);

  msg_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ltsrpc.Status.msg)
}
inline void Status::set_msg(const char* value, size_t size) {

  msg_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ltsrpc.Status.msg)
}
inline std::string* Status::mutable_msg() {

  // @@protoc_insertion_point(field_mutable:ltsrpc.Status.msg)
  return msg_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* Status::release_msg() {
  // @@protoc_insertion_point(field_release:ltsrpc.Status.msg)

  return msg_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void Status::set_allocated_msg(std::string* msg) {
  if (msg != nullptr) {

  } else {

  }
  msg_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), msg);
  // @@protoc_insertion_point(field_set_allocated:ltsrpc.Status.msg)
}

// -------------------------------------------------------------------

// Member

// uint64 member_id = 1;
inline void Member::clear_member_id() {
  member_id_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Member::member_id() const {
  // @@protoc_insertion_point(field_get:ltsrpc.Member.member_id)
  return member_id_;
}
inline void Member::set_member_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {

  member_id_ = value;
  // @@protoc_insertion_point(field_set:ltsrpc.Member.member_id)
}

// string name = 2;
inline void Member::clear_name() {
  name_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& Member::name() const {
  // @@protoc_insertion_point(field_get:ltsrpc.Member.name)
  return name_.GetNoArena();
}
inline void Member::set_name(const std::string& value) {

  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ltsrpc.Member.name)
}
inline void Member::set_name(std::string&& value) {

  name_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ltsrpc.Member.name)
}
inline void Member::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);

  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ltsrpc.Member.name)
}
inline void Member::set_name(const char* value, size_t size) {

  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ltsrpc.Member.name)
}
inline std::string* Member::mutable_name() {

  // @@protoc_insertion_point(field_mutable:ltsrpc.Member.name)
  return name_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* Member::release_name() {
  // @@protoc_insertion_point(field_release:ltsrpc.Member.name)

  return name_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void Member::set_allocated_name(std::string* name) {
  if (name != nullptr) {

  } else {

  }
  name_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:ltsrpc.Member.name)
}

// repeated string peer_urls = 3;
inline int Member::peer_urls_size() const {
  return peer_urls_.size();
}
inline void Member::clear_peer_urls() {
  peer_urls_.Clear();
}
inline const std::string& Member::peer_urls(int index) const {
  // @@protoc_insertion_point(field_get:ltsrpc.Member.peer_urls)
  return peer_urls_.Get(index);
}
inline std::string* Member::mutable_peer_urls(int index) {
  // @@protoc_insertion_point(field_mutable:ltsrpc.Member.peer_urls)
  return peer_urls_.Mutable(index);
}
inline void Member::set_peer_urls(int index, const std::string& value) {
  // @@protoc_insertion_point(field_set:ltsrpc.Member.peer_urls)
  peer_urls_.Mutable(index)->assign(value);
}
inline void Member::set_peer_urls(int index, std::string&& value) {
  // @@protoc_insertion_point(field_set:ltsrpc.Member.peer_urls)
  peer_urls_.Mutable(index)->assign(std::move(value));
}
inline void Member::set_peer_urls(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  peer_urls_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:ltsrpc.Member.peer_urls)
}
inline void Member::set_peer_urls(int index, const char* value, size_t size) {
  peer_urls_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:ltsrpc.Member.peer_urls)
}
inline std::string* Member::add_peer_urls() {
  // @@protoc_insertion_point(field_add_mutable:ltsrpc.Member.peer_urls)
  return peer_urls_.Add();
}
inline void Member::add_peer_urls(const std::string& value) {
  peer_urls_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:ltsrpc.Member.peer_urls)
}
inline void Member::add_peer_urls(std::string&& value) {
  peer_urls_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:ltsrpc.Member.peer_urls)
}
inline void Member::add_peer_urls(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  peer_urls_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:ltsrpc.Member.peer_urls)
}
inline void Member::add_peer_urls(const char* value, size_t size) {
  peer_urls_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:ltsrpc.Member.peer_urls)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
Member::peer_urls() const {
  // @@protoc_insertion_point(field_list:ltsrpc.Member.peer_urls)
  return peer_urls_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
Member::mutable_peer_urls() {
  // @@protoc_insertion_point(field_mutable_list:ltsrpc.Member.peer_urls)
  return &peer_urls_;
}

// repeated string client_urls = 4;
inline int Member::client_urls_size() const {
  return client_urls_.size();
}
inline void Member::clear_client_urls() {
  client_urls_.Clear();
}
inline const std::string& Member::client_urls(int index) const {
  // @@protoc_insertion_point(field_get:ltsrpc.Member.client_urls)
  return client_urls_.Get(index);
}
inline std::string* Member::mutable_client_urls(int index) {
  // @@protoc_insertion_point(field_mutable:ltsrpc.Member.client_urls)
  return client_urls_.Mutable(index);
}
inline void Member::set_client_urls(int index, const std::string& value) {
  // @@protoc_insertion_point(field_set:ltsrpc.Member.client_urls)
  client_urls_.Mutable(index)->assign(value);
}
inline void Member::set_client_urls(int index, std::string&& value) {
  // @@protoc_insertion_point(field_set:ltsrpc.Member.client_urls)
  client_urls_.Mutable(index)->assign(std::move(value));
}
inline void Member::set_client_urls(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  client_urls_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:ltsrpc.Member.client_urls)
}
inline void Member::set_client_urls(int index, const char* value, size_t size) {
  client_urls_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:ltsrpc.Member.client_urls)
}
inline std::string* Member::add_client_urls() {
  // @@protoc_insertion_point(field_add_mutable:ltsrpc.Member.client_urls)
  return client_urls_.Add();
}
inline void Member::add_client_urls(const std::string& value) {
  client_urls_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:ltsrpc.Member.client_urls)
}
inline void Member::add_client_urls(std::string&& value) {
  client_urls_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:ltsrpc.Member.client_urls)
}
inline void Member::add_client_urls(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  client_urls_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:ltsrpc.Member.client_urls)
}
inline void Member::add_client_urls(const char* value, size_t size) {
  client_urls_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:ltsrpc.Member.client_urls)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
Member::client_urls() const {
  // @@protoc_insertion_point(field_list:ltsrpc.Member.client_urls)
  return client_urls_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
Member::mutable_client_urls() {
  // @@protoc_insertion_point(field_mutable_list:ltsrpc.Member.client_urls)
  return &client_urls_;
}

// int32 leader_priority = 5;
inline void Member::clear_leader_priority() {
  leader_priority_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Member::leader_priority() const {
  // @@protoc_insertion_point(field_get:ltsrpc.Member.leader_priority)
  return leader_priority_;
}
inline void Member::set_leader_priority(::PROTOBUF_NAMESPACE_ID::int32 value) {

  leader_priority_ = value;
  // @@protoc_insertion_point(field_set:ltsrpc.Member.leader_priority)
}

// -------------------------------------------------------------------

// RequestHeader

// uint32 cluster_id = 1;
inline void RequestHeader::clear_cluster_id() {
  cluster_id_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 RequestHeader::cluster_id() const {
  // @@protoc_insertion_point(field_get:ltsrpc.RequestHeader.cluster_id)
  return cluster_id_;
}
inline void RequestHeader::set_cluster_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {

  cluster_id_ = value;
  // @@protoc_insertion_point(field_set:ltsrpc.RequestHeader.cluster_id)
}

// -------------------------------------------------------------------

// ResponseHeader

// uint32 cluster_id = 1;
inline void ResponseHeader::clear_cluster_id() {
  cluster_id_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ResponseHeader::cluster_id() const {
  // @@protoc_insertion_point(field_get:ltsrpc.ResponseHeader.cluster_id)
  return cluster_id_;
}
inline void ResponseHeader::set_cluster_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {

  cluster_id_ = value;
  // @@protoc_insertion_point(field_set:ltsrpc.ResponseHeader.cluster_id)
}

// .ltsrpc.Status status = 2;
inline bool ResponseHeader::has_status() const {
  return this != internal_default_instance() && status_ != nullptr;
}
inline void ResponseHeader::clear_status() {
  if (GetArenaNoVirtual() == nullptr && status_ != nullptr) {
    delete status_;
  }
  status_ = nullptr;
}
inline const ::ltsrpc::Status& ResponseHeader::status() const {
  const ::ltsrpc::Status* p = status_;
  // @@protoc_insertion_point(field_get:ltsrpc.ResponseHeader.status)
  return p != nullptr ? *p : *reinterpret_cast<const ::ltsrpc::Status*>(
      &::ltsrpc::_Status_default_instance_);
}
inline ::ltsrpc::Status* ResponseHeader::release_status() {
  // @@protoc_insertion_point(field_release:ltsrpc.ResponseHeader.status)

  ::ltsrpc::Status* temp = status_;
  status_ = nullptr;
  return temp;
}
inline ::ltsrpc::Status* ResponseHeader::mutable_status() {

  if (status_ == nullptr) {
    auto* p = CreateMaybeMessage<::ltsrpc::Status>(GetArenaNoVirtual());
    status_ = p;
  }
  // @@protoc_insertion_point(field_mutable:ltsrpc.ResponseHeader.status)
  return status_;
}
inline void ResponseHeader::set_allocated_status(::ltsrpc::Status* status) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete status_;
  }
  if (status) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      status = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, status, submessage_arena);
    }

  } else {

  }
  status_ = status;
  // @@protoc_insertion_point(field_set_allocated:ltsrpc.ResponseHeader.status)
}

// -------------------------------------------------------------------

// GetMembersRequest

// .ltsrpc.RequestHeader header = 1;
inline bool GetMembersRequest::has_header() const {
  return this != internal_default_instance() && header_ != nullptr;
}
inline void GetMembersRequest::clear_header() {
  if (GetArenaNoVirtual() == nullptr && header_ != nullptr) {
    delete header_;
  }
  header_ = nullptr;
}
inline const ::ltsrpc::RequestHeader& GetMembersRequest::header() const {
  const ::ltsrpc::RequestHeader* p = header_;
  // @@protoc_insertion_point(field_get:ltsrpc.GetMembersRequest.header)
  return p != nullptr ? *p : *reinterpret_cast<const ::ltsrpc::RequestHeader*>(
      &::ltsrpc::_RequestHeader_default_instance_);
}
inline ::ltsrpc::RequestHeader* GetMembersRequest::release_header() {
  // @@protoc_insertion_point(field_release:ltsrpc.GetMembersRequest.header)

  ::ltsrpc::RequestHeader* temp = header_;
  header_ = nullptr;
  return temp;
}
inline ::ltsrpc::RequestHeader* GetMembersRequest::mutable_header() {

  if (header_ == nullptr) {
    auto* p = CreateMaybeMessage<::ltsrpc::RequestHeader>(GetArenaNoVirtual());
    header_ = p;
  }
  // @@protoc_insertion_point(field_mutable:ltsrpc.GetMembersRequest.header)
  return header_;
}
inline void GetMembersRequest::set_allocated_header(::ltsrpc::RequestHeader* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete header_;
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }

  } else {

  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:ltsrpc.GetMembersRequest.header)
}

// -------------------------------------------------------------------

// GetMembersResponse

// .ltsrpc.ResponseHeader header = 1;
inline bool GetMembersResponse::has_header() const {
  return this != internal_default_instance() && header_ != nullptr;
}
inline void GetMembersResponse::clear_header() {
  if (GetArenaNoVirtual() == nullptr && header_ != nullptr) {
    delete header_;
  }
  header_ = nullptr;
}
inline const ::ltsrpc::ResponseHeader& GetMembersResponse::header() const {
  const ::ltsrpc::ResponseHeader* p = header_;
  // @@protoc_insertion_point(field_get:ltsrpc.GetMembersResponse.header)
  return p != nullptr ? *p : *reinterpret_cast<const ::ltsrpc::ResponseHeader*>(
      &::ltsrpc::_ResponseHeader_default_instance_);
}
inline ::ltsrpc::ResponseHeader* GetMembersResponse::release_header() {
  // @@protoc_insertion_point(field_release:ltsrpc.GetMembersResponse.header)

  ::ltsrpc::ResponseHeader* temp = header_;
  header_ = nullptr;
  return temp;
}
inline ::ltsrpc::ResponseHeader* GetMembersResponse::mutable_header() {

  if (header_ == nullptr) {
    auto* p = CreateMaybeMessage<::ltsrpc::ResponseHeader>(GetArenaNoVirtual());
    header_ = p;
  }
  // @@protoc_insertion_point(field_mutable:ltsrpc.GetMembersResponse.header)
  return header_;
}
inline void GetMembersResponse::set_allocated_header(::ltsrpc::ResponseHeader* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete header_;
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }

  } else {

  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:ltsrpc.GetMembersResponse.header)
}

// repeated .ltsrpc.Member members = 2;
inline int GetMembersResponse::members_size() const {
  return members_.size();
}
inline void GetMembersResponse::clear_members() {
  members_.Clear();
}
inline ::ltsrpc::Member* GetMembersResponse::mutable_members(int index) {
  // @@protoc_insertion_point(field_mutable:ltsrpc.GetMembersResponse.members)
  return members_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ltsrpc::Member >*
GetMembersResponse::mutable_members() {
  // @@protoc_insertion_point(field_mutable_list:ltsrpc.GetMembersResponse.members)
  return &members_;
}
inline const ::ltsrpc::Member& GetMembersResponse::members(int index) const {
  // @@protoc_insertion_point(field_get:ltsrpc.GetMembersResponse.members)
  return members_.Get(index);
}
inline ::ltsrpc::Member* GetMembersResponse::add_members() {
  // @@protoc_insertion_point(field_add:ltsrpc.GetMembersResponse.members)
  return members_.Add();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ltsrpc::Member >&
GetMembersResponse::members() const {
  // @@protoc_insertion_point(field_list:ltsrpc.GetMembersResponse.members)
  return members_;
}

// .ltsrpc.Member leader = 3;
inline bool GetMembersResponse::has_leader() const {
  return this != internal_default_instance() && leader_ != nullptr;
}
inline void GetMembersResponse::clear_leader() {
  if (GetArenaNoVirtual() == nullptr && leader_ != nullptr) {
    delete leader_;
  }
  leader_ = nullptr;
}
inline const ::ltsrpc::Member& GetMembersResponse::leader() const {
  const ::ltsrpc::Member* p = leader_;
  // @@protoc_insertion_point(field_get:ltsrpc.GetMembersResponse.leader)
  return p != nullptr ? *p : *reinterpret_cast<const ::ltsrpc::Member*>(
      &::ltsrpc::_Member_default_instance_);
}
inline ::ltsrpc::Member* GetMembersResponse::release_leader() {
  // @@protoc_insertion_point(field_release:ltsrpc.GetMembersResponse.leader)

  ::ltsrpc::Member* temp = leader_;
  leader_ = nullptr;
  return temp;
}
inline ::ltsrpc::Member* GetMembersResponse::mutable_leader() {

  if (leader_ == nullptr) {
    auto* p = CreateMaybeMessage<::ltsrpc::Member>(GetArenaNoVirtual());
    leader_ = p;
  }
  // @@protoc_insertion_point(field_mutable:ltsrpc.GetMembersResponse.leader)
  return leader_;
}
inline void GetMembersResponse::set_allocated_leader(::ltsrpc::Member* leader) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete leader_;
  }
  if (leader) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      leader = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, leader, submessage_arena);
    }

  } else {

  }
  leader_ = leader;
  // @@protoc_insertion_point(field_set_allocated:ltsrpc.GetMembersResponse.leader)
}

// .ltsrpc.Member etcd_leader = 4;
inline bool GetMembersResponse::has_etcd_leader() const {
  return this != internal_default_instance() && etcd_leader_ != nullptr;
}
inline void GetMembersResponse::clear_etcd_leader() {
  if (GetArenaNoVirtual() == nullptr && etcd_leader_ != nullptr) {
    delete etcd_leader_;
  }
  etcd_leader_ = nullptr;
}
inline const ::ltsrpc::Member& GetMembersResponse::etcd_leader() const {
  const ::ltsrpc::Member* p = etcd_leader_;
  // @@protoc_insertion_point(field_get:ltsrpc.GetMembersResponse.etcd_leader)
  return p != nullptr ? *p : *reinterpret_cast<const ::ltsrpc::Member*>(
      &::ltsrpc::_Member_default_instance_);
}
inline ::ltsrpc::Member* GetMembersResponse::release_etcd_leader() {
  // @@protoc_insertion_point(field_release:ltsrpc.GetMembersResponse.etcd_leader)

  ::ltsrpc::Member* temp = etcd_leader_;
  etcd_leader_ = nullptr;
  return temp;
}
inline ::ltsrpc::Member* GetMembersResponse::mutable_etcd_leader() {

  if (etcd_leader_ == nullptr) {
    auto* p = CreateMaybeMessage<::ltsrpc::Member>(GetArenaNoVirtual());
    etcd_leader_ = p;
  }
  // @@protoc_insertion_point(field_mutable:ltsrpc.GetMembersResponse.etcd_leader)
  return etcd_leader_;
}
inline void GetMembersResponse::set_allocated_etcd_leader(::ltsrpc::Member* etcd_leader) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete etcd_leader_;
  }
  if (etcd_leader) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      etcd_leader = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, etcd_leader, submessage_arena);
    }

  } else {

  }
  etcd_leader_ = etcd_leader;
  // @@protoc_insertion_point(field_set_allocated:ltsrpc.GetMembersResponse.etcd_leader)
}

// -------------------------------------------------------------------

// GetTxnTimestampCtx

// uint64 txn_id = 1;
inline void GetTxnTimestampCtx::clear_txn_id() {
  txn_id_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 GetTxnTimestampCtx::txn_id() const {
  // @@protoc_insertion_point(field_get:ltsrpc.GetTxnTimestampCtx.txn_id)
  return txn_id_;
}
inline void GetTxnTimestampCtx::set_txn_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {

  txn_id_ = value;
  // @@protoc_insertion_point(field_set:ltsrpc.GetTxnTimestampCtx.txn_id)
}

// uint64 txn_ts = 2;
inline void GetTxnTimestampCtx::clear_txn_ts() {
  txn_ts_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 GetTxnTimestampCtx::txn_ts() const {
  // @@protoc_insertion_point(field_get:ltsrpc.GetTxnTimestampCtx.txn_ts)
  return txn_ts_;
}
inline void GetTxnTimestampCtx::set_txn_ts(::PROTOBUF_NAMESPACE_ID::uint64 value) {

  txn_ts_ = value;
  // @@protoc_insertion_point(field_set:ltsrpc.GetTxnTimestampCtx.txn_ts)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace ltsrpc

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::ltsrpc::StatusCode> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::ltsrpc::StatusCode>() {
  return ::ltsrpc::StatusCode_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ltsrpc_2eproto
